### ISSUE TITLE
bulk operations, esp. intersection

### ISSUE THREAD

**Issue by jwaldmann** [haskell-perf/dictionaries#1]
I'd like to see benchmarks for bulk operations on maps. I think `intersection` is important (composition
of relations, JOIN for DB tables).

I have an application (and related benchmark) where this is crucial (https://gitlab.imn.htwk-leipzig.de/waldmann/containers-benchmark) but I think it is too large to be included here.

For a test case like "intersect two (large) maps" - what would be the best way to generate them and measure the cost? If we just compute one intersection - it could take less time than construction from lists (it should - that's the whole point of having these bulk operations).

So - compute a lot of intersections? Like, the transitive closure of a relation, by just iterating until fixpoint is reached? But, there may be more clever algorithms for transitive closure...

Or, is there a way to set up the benchmark so that constructing maps is "free"?

**Comment by chrisdone** [comment]
I think you can do the simplest thing first.

If there are intersections for all the dictionary types, I think we can then probably just generate a map of random keys and deepseq it. Then the benchmark itself will run after that. Use the same seed for generating each map and the keys will be the same. Do an intersection and see what the time is like.

Criterion has the `env` function for this purpose.

If the output basically matches your own conclusions, then the simple approach is satisfactory.

Relatedly, I'm also interested in `insertWith`-like operations, for doing histograms.

**Comment by chrisdone** [comment]
I think the one you contributed is a pretty good start.

**Comment by unhammer** [comment]
On a related note, bytestring-trie [now has intersectBy](https://github.com/wrengr/bytestring-trie/issues/1) but it's not on Hackage yet

**Comment by unhammer** [comment]
which in my tests slightly outperforms the other maps: https://github.com/haskell-perf/dictionaries/compare/master...unhammer:trie-isect?expand=1 – but of course not mergeable into haskell-perf until there's a Hackage release of Data.Trie with it. Thought I'd mention it though in case others are interested in such operations.
