### ISSUE TITLE
Which license is this repository under?

### ISSUE THREAD

**Issue by anfelor** [haskell-perf/dictionaries#10]
A part of the [algebraic-graphs GSoC](https://summer.haskell.org/ideas.html#graphs) proposal is to develop a benchmark suite. I have started such an attempt in [a clone of this repository](https://github.com/anfelor/graph-benchmarks). However, it is unclear to me, if it could be merged into the main alga repository with is MIT licensed.

What are your thoughts about this? Does no license mean public domain? Or something more restricted?

**Comment by chrisdone** [comment]
I can put a BSD/MIT license in the repo. It's intended to be liberal.

**Comment by anfelor** [comment]
I am not sure, it is legal to do this as others have contributed to this repository already. But I don't think it will be a problem. Thank you for resolving this issue so fast!
