### ISSUE TITLE
Funky numbers for Int Lookup (Randomized)

### ISSUE THREAD

**Issue by typesanitizer** [haskell-perf/dictionaries#12]
Highlighted in **bold**

|Name|10|100|1000|10000|100000|1000000|
|---|---|---|---|---|---|---|
|Data.Map.Lazy|17.11 ns|26.66 ns|35.41 ns|56.09 ns|**75.62 ns**|**64.22 ns**|
|Data.Map.Strict|17.51 ns|26.25 ns|35.62 ns|51.95 ns|**71.76 ns**|**72.39 ns**|
|Data.HashMap.Lazy|**26.63 ns**|**29.82 ns**|**24.89 ns**|28.10 ns|40.25 ns|44.14 ns|
|Data.HashMap.Strict|**27.19 ns**|**31.86 ns**|**25.14 ns**|32.25 ns|40.18 ns|48.39 ns|
|Data.IntMap.Lazy|17.70 ns|27.10 ns|35.27 ns|42.06 ns|49.01 ns|66.90 ns|
|Data.IntMap.Strict|17.91 ns|26.49 ns|33.68 ns|41.21 ns|47.23 ns|67.03 ns|

**Comment by chrisdone** [comment]
Why is that funky? 

* Data.HashMap demonstrates a high constant factor overhead on the first 1000 lookups.
* Data.Map is slower than HashMap and IntMap because it uses a different data structure.

**Comment by chrisdone** [comment]
If you're referring to the fluctuation up and down in time, I think it's severe inflation. I'll do a re-run on my machine and see if I get more increasing numbers.

**Comment by typesanitizer** [comment]
I meant the non-monotonic behaviour, not the comparison with other structures.

**Comment by chrisdone** [comment]
I think I figured it out. It's the input data itself. I'm generating a random list of numbers and doing a lookup. It seems that the latter key is coincidentally less expensive to lookup.

I don't think there's much I can do about this and other than explain it in the README for the random section.

**Comment by chrisdone** [comment]
Or maybe I can just lookup _all_ keys in a loop and then measure that speed. :thinking:

**Comment by chrisdone** [comment]
That yields increasing results:

|Name|10|100|1000|10000|100000|1000000|
|---|---|---|---|---|---|---|
|Data.Map.Lazy|113.9 ns|1.697 μs|67.91 μs|1225 μs|21.89 ms|556.1 ms|
|Data.Map.Strict|113.5 ns|1.782 μs|67.75 μs|1258 μs|21.68 ms|543.4 ms|
|Data.HashMap.Lazy|156.9 ns|2.151 μs|31.06 μs|531.4 μs|17.10 ms|339.4 ms|
|Data.HashMap.Strict|166.1 ns|2.157 μs|27.52 μs|517.6 μs|16.62 ms|335.9 ms|
|Data.IntMap.Lazy|138.7 ns|1.830 μs|71.38 μs|1203 μs|24.10 ms|649.5 ms|
|Data.IntMap.Strict|138.6 ns|1.835 μs|70.28 μs|1192 μs|25.18 ms|629.8 ms|

**Comment by typesanitizer** [comment]
Thanks for the update!
