### ISSUE TITLE
defaulted to Integer (in insertBSMonotonic)

### ISSUE THREAD

**Issue by jwaldmann** [haskell-perf/dictionaries#3]
Not sure whether that's relevant: in `insertBSMonotonic` some indices are Integer (not Int).
Adding the type decl. doesn't change much.

**Comment by chrisdone** [comment]
I think this is fixed.

**Comment by chrisdone** [comment]
Or not a problem, from the current code I see in `insertBSMonotonic`, the ints are generated via `env` which is before the benchmark begins.
