### ISSUE TITLE
separate repo for sets?

### ISSUE THREAD

**Issue by unhammer** [haskell-perf/dictionaries#6]
Should there be a separate repo for those that can't have values (without hacking values into keys)? E.g.
* [Data.HashSet](http://hackage.haskell.org/package/unordered-containers-0.2.8.0/docs/Data-HashSet.html)
* [Data.Set](http://hackage.haskell.org/package/containers-0.5.10.1/docs/Data-Set.html)
* [Data.IntSet](http://hackage.haskell.org/package/containers-0.5.10.1/docs/Data-IntSet.html)
* [Data.DAWG.Packed](http://hackage.haskell.org/package/packed-dawg-0.2.0.8/docs/Data-DAWG-Packed.html )

( [Data.BloomFilter](https://hackage.haskell.org/package/bloomfilter-2.0.1.0/docs/Data-BloomFilter.html) is perhaps yet another category)

**Comment by chrisdone** [comment]
Sure, I think a `sets` repo would be perfectly reasonable.

**Comment by chrisdone** [comment]
Feel free to clone this one and change the data types to set, hashset, intset, bloom filter.

I think that for bloom and packed, you would make a separate benchmark group testing e.g. the probabilistic bloom filter against regular sets as a baseline, but making clear the two are different.

**Comment by unhammer** [comment]
here's a first stab: https://github.com/haskell-perf/dictionaries/compare/master...unhammer:sets

**Comment by unhammer** [comment]
did https://github.com/unhammer/dictionaries/tree/sets look ok, or was anything amiss?

**Comment by chrisdone** [comment]
Oh that looks good. I just missed it. I've added you as a member of the org so you can add it when you're ready.

**Comment by unhammer** [comment]
Pushed to https://github.com/haskell-perf/sets – should I note in the beginning of the README about bloom filter being probabilistic?

**Comment by chrisdone** [comment]
Sure, seems reasonable.

**Comment by unhammer** [comment]
Done; maybe we can close this issue?
